theme: jekyll-theme-cayman

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-261610-9

collections:
  drivers:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drivers" # previously `post` in Jekyll 2.2.
    values:
      layout: "driver"

plugins:
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
